# -*- coding: utf-8 -*-
"""S1_IP_exercice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tbeucler/2024_UNIL_Geoinformatique/blob/main/Geoinformatique_I/IP/Exercices_IP/S1_IP_exercice.ipynb

## Exercice 1 - Introduction aux bases de la programmation

### Premier code de Python :

Utiliser la fonction "print()" pour afficher le texte "Hello world".
"""

# Premier script : "Hello world"
print("_____")

"""### Variables et types de données :

"""

# Initialiser des données

x = ____    # Remplacer par une valeur entière (integer)
y = ____    # Remplacer par une valeur décimale (float)
z = "____"  # Remplacer par une chaîne de caractères. Par exemple "Python"

"""Maintenant vérifions le type de ces variables à l'aide de la fonction "type()"
"""

# Comment vérifier le type ?
print(type(__))  # Affiche le type de x
print(type(__))  # Affiche le type de y
print(type(__))  # Affiche le type de z

"""### Opérations arithmétiques :"""

a = ___  # Remplacer par une valeur entière
b = ___  # Remplacer par une valeur entière

# Opérations arithmétiques
addition = a + b  # Calcul de l'addition
soustraction = ____  # Calcul de la soustraction entre a et b
multiplication = ____  # Calcul de la multiplication entre a et b
division = ____  # Calcul de la division de a par b

# Afficher les résultats
print("Addition:", ______)
print("Soustraction:", ______)
print("Multiplication:", ______)
print("Division:", ______)

"""### Calcul d'émissions de CO2 :"""

# Données
distance_km = ____  # Distance parcourue en kilomètres
consommation_essence_litres_km = ____  # Consommation d'essence en litres par km

# Calcul des émissions de CO2 en kilogrammes
# Le facteur 2,3 est une estimation générale de la quantité de dioxyde de carbone (CO2) émise en kilogrammes par litre de carburant brûlé.
# Il est utilisé pour convertir la consommation d'essence en émissions de CO2.
emissions_CO2_kg = (______ * _____) * 2.3

# Afficher le résultat
print("Les émissions de CO2 pour", _____, "km parcourus sont de", _______, "grammes.")

"""### Calcul de la consommation d'énergie"""

# Données
puissance_appareil = ______  # Puissance de l'appareil en watts
temps_utilisation_heures = ___  # Temps d'utilisation en heures par jour

# Calcul de la consommation d'énergie quotidienne en kilowatt-heures (kWh)
# La division par 1000 est nécessaire pour convertir la puissance de l'appareil (exprimée en watts) en kilowatts,
# car 1 kilowatt équivaut à 1000 watts.
consommation_quotidienne_kWh = (_______ * ______) / 1000

# Afficher le résultat
print("La consommation d'énergie quotidienne de l'appareil est de", ______, "kWh.")